name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.9'

    - name: Make Gradle Wrapper executable
      working-directory: server
      run: chmod +x ./gradlew

    - name: Build with Gradle Wrapper
      working-directory: server
      run: ./gradlew build

    - name: Start Docker Compose
      working-directory: server
      run: docker compose -f compose.yaml up -d

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Submit Gradle dependency graph
      uses: gradle/actions/dependency-submission@v4
